import TopNav from "@/components/TopNav";
import Footer from "@/components/Footer";
import SectionStrip from "@/components/SectionStrip";

export const metadata = {
  title: "Security — Skein",
  description: "Skein is local-first. The daemon binds to 127.0.0.1. Your code never leaves your laptop on the free tier.",
};

export default function SecurityPage() {
  return (
    <main className="min-h-screen">
      <TopNav />

      <section className="max-w-content mx-auto px-8 sm:px-12 pt-12 pb-10">
        <div className="font-mono text-[0.6875rem] tracking-[0.12em] uppercase text-fg-2 mb-3">
          security
        </div>
        <h1 className="tagline text-3xl sm:text-4xl text-fg-0 mb-4 max-w-[36rem]">
          Local-first by default. Your code never leaves the laptop.
        </h1>
        <p className="text-fg-1 max-w-[36rem] leading-[1.55]">
          Skein&apos;s threat model is &quot;everything stays on{" "}
          <code className="font-mono text-fg-0">127.0.0.1</code> unless you explicitly opt in.&quot;
        </p>
      </section>

      <SectionStrip label="what stays local" />
      <section className="max-w-content mx-auto px-8 sm:px-12 py-10 grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-bg-1 border border-divider rounded-lg p-6">
          <div className="font-mono text-[0.6875rem] tracking-[0.1em] uppercase text-fg-2 mb-3">
            free tier · default install
          </div>
          <h3 className="card-title text-lg text-fg-0 mb-2">Everything.</h3>
          <ul className="text-sm text-fg-1 leading-[1.7] mt-2 space-y-1">
            <li>• Source code chunks — never leave disk.</li>
            <li>• Decisions, observations, recall queries — local SQLite.</li>
            <li>• Embeddings — local hash provider by default; switch to Gemini opt-in.</li>
            <li>• Bearer token — generated per machine, never reused.</li>
          </ul>
        </div>
        <div className="bg-bg-1 border border-divider rounded-lg p-6">
          <div className="font-mono text-[0.6875rem] tracking-[0.1em] uppercase text-fg-2 mb-3">
            opt-in · cloud tier
          </div>
          <h3 className="card-title text-lg text-fg-0 mb-2">What changes.</h3>
          <ul className="text-sm text-fg-1 leading-[1.7] mt-2 space-y-1">
            <li>• You bring an embedding key (Gemini, OpenAI) — chunks are sent to embed.</li>
            <li>• Team sync (planned) — encrypted-at-rest blob replicates between machines.</li>
            <li>• Telemetry stays off unless explicitly enabled.</li>
          </ul>
        </div>
      </section>

      <SectionStrip label="cryptography & secrets" />
      <section className="max-w-content mx-auto px-8 sm:px-12 py-10">
        <p className="max-w-[44rem] text-[0.9375rem] text-fg-1 leading-[1.65]">
          The bearer token is generated by the daemon on first launch and stored at{" "}
          <code className="font-mono text-fg-0">~/.config/skein/token</code> with 0600
          permissions. It is required for every MCP request — even from{" "}
          <code className="font-mono text-fg-0">127.0.0.1</code> — to prevent other local
          processes from talking to the daemon without permission. Rotate it any time
          with <code className="font-mono text-fg-0">skein rotate-token</code>.
        </p>
        <p className="mt-6 font-mono text-xs text-fg-3">
          More detail coming in iter 22.1 — including a threat-model write-up and SBOM.
        </p>
      </section>

      <Footer />
    </main>
  );
}
